'''Module docstring as;ldkfj'''

import os


class TestClass:
    '''Test'''

    def __init__(self):
        self.blah = 12


def test2():
    '''doc string'''
    return 'blah'
 
def test():
    '''yo'''
    print(os)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)
    print(os)
    print(' Hello World, my name is')
    print()
    print()
    print()
    print("Test")
    print()
    print(0)


if __name__ == '__main__':
    test()
                    